var obj1 = {1: "Tim", "2": "Rick", true: "Jill"};
console.log(obj1);
var map1 = new Map([[1,'A'], [2, 'B']]);
console.log(map1);
var key1 = function(){};
var key2 = {5: "five"};
map1.set(key1, "This is function");
map1.set(key2, "Object key");
console.log(map1.has(1));
map1.delete(1);
//map1.clear();
console.log(map1.size);
console.log(map1.get(key1));
console.log(map1.get(key2));
console.log(map1.keys());
console.log(map1.values());
console.log(map1.entries());
var weMa1 = new WeakMap();
//weMa1.set("key1", 10); weMa1.set(10, "ten");
weMa1.set({10: "ten"}, "Only object may be used as a key");
console.log(weMa1);
var obj1 = {};
var arr1 = [2, 4, 6];
var set1 = new Set([10, 19, 10, "true", true, "true", obj1, obj1]);
console.log(set1);
set1.delete(10);
set1.add({3: "black"});
set1.add(arr1);
console.log(set1);
console.log(set1.has(arr1));
console.log(set1.entries());
console.log(set1.values());
//set1.clear();
var set2 = new Set(map1);
console.log(set2);

var weSe = new WeakSet();
var obj2 = {3: "black"};
weSe.add({3: "black"});
weSe.add({3: "black"});
weSe.add(obj2); weSe.add(obj2);
console.log(weSe);
console.log(weSe.has(obj2));
