//console.log(String.fromCharCode(65, 66, 67) + " " String.fromCodePoint(0x404));
let quotes = "What goes around, comes around.";
let adWords = "add new words";
//console.log(quotes.charAt(5) + " " + quotes.charCodeAt(5) + " " + quotes.codePointAt(5));
//console.log(quotes.concat(" Good", " quote, ", "huh ", adWords));
//console.log(quotes.includes("com", 10));
//console.log(quotes.endsWith("und", 16));
//console.log(quotes.indexOf("ar"));
//console.log(quotes.lastIndexOf("ar"));
//console.log("MDN".link('https://developer.mozilla.org'));
//console.log(quotes.match(/a[a-z]/gi));
//console.log(quotes.search(/a[a-r]/gi));
//console.log("12345ABC".replace(/345/gi, "$&|"));
//console.log("12345ABC".replace(/34/gi, "|$`"));
//console.log("12345ABC".replace(/34/gi, "$'|"));
//console.log(quotes.repeat(3));
//console.log("0123456789".slice(4, -2));
//console.log(quotes.split(" ", 2));
//console.log(quotes.startsWith("com", 18));
//console.log("01234567".substr(2, 3));
//console.log("012345".substring(3, 0));
//console.log("This is uppeR".toUpperCase());
//console.log("This is LOWER".toLowerCase());
//console.log("     Delete tabs     ".trim());
//console.log(String.fromCodePoint(0x1f3c4));
